name: places
description: Surf flutter course app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # поддержка svg
  flutter_svg: ^0.19.1
  dio: ^3.0.10
  provider: ^4.3.3
  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # линтер. настройки в analysis_options.yaml
  lint: 1.3.0

flutter:
  uses-material-design: true

  assets:
    - res/
    - res/svg/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf