name: places
description: Surf flutter course app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # поддержка svg
  flutter_svg: ^0.19.3
  dio: ^3.0.10
  provider: ^4.3.3
  rxdart: ^0.25.0

  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

  flutter_bloc: ^6.1.3
  equatable: ^2.0.0

  redux: ^4.0.0
  flutter_redux: ^0.7.0

  # для mwwm
  mwwm: ^0.1.3-dev.3
  relation: ^0.0.4-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^1.1.2
  build_runner: ^1.11.1

  # линтер. настройки в analysis_options.yaml
  lint: 1.3.0

flutter:
  uses-material-design: true

  assets:
    - res/
    - res/svg/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf