name: places
description: Surf flutter course app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # поддержка svg
  flutter_svg: ^0.19.3

  dio: ^3.0.10
  provider: ^4.3.3
  rxdart: ^0.25.0

  # для mwwm
  mwwm: ^0.1.3-dev.3
  relation: ^0.0.4-dev.1

  shared_preferences: ^0.5.0
  json_annotation: ^3.1.1

  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.3.0
  path_provider: ^0.5.0
  path: ^1.8.0

  image_picker: ^0.6.7+22

  uuid: ^2.2.2

  geolocator: ^6.2.0

  yandex_mapkit: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.1
  json_serializable: ^3.5.1
  moor_generator: ^3.4.0

  # линтер. настройки в analysis_options.yaml
  lint: 1.3.0

flutter:
  uses-material-design: true

  assets:
    - res/
    - res/svg/
    - res/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf